MvcStok/Controllers/MusterıController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class MusterıController : Controller
    {
        // GET: Musterı
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            var degerler=from d in db.TBLMUSTERILER select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());  
            //var degerler = db.TBLMUSTERILER.ToList();
            //return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {

            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();

        }
        public ActionResult SIL(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri); 
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusterıGetır(int id)
        {
            var mus = db.TBLMUSTERILER.Find(id);
            return View("MusterıGetır",mus);

        }
        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musterı = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musterı.MUSTERIAD = p1.MUSTERIAD;
            musterı.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");   

        }

    }
}

MvcStok/Views/Musterı/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index","Musterı",FormMethod.Get))
            {
    <p>
        <b>Aranacak Müşteri Adı:</b> @Html.TextBox("p")
    <input type="submit" value="Ara" />
    </p>

            }

<table class="table table-bordered">
    <tr>
        <th>MUSTERI ID</th>
        <th>MUSTERI ADI</th>
        <th>MUSTERI SOYADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT</th>
        



    </tr>
    <tbody>
        @foreach (var mus in Model)
        {
            <tr>
                <th>@mus.MUSTERIID</th>
                <td>@mus.MUSTERIAD</td>
                <td>@mus.MUSTERISOYAD</td>
                <td><a href="/Musterı/SIL/@mus.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/Musterı/MusterıGetır/@mus.MUSTERIID" class="btn btn-success">GUNCELLE</a></td>
                <td>@Html.ActionLink("SİL BUTONU","SIL",new { id=mus.MUSTERIID },new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor Musunuz?')" })</td>
                }
            </tr>
        }
    </tbody>
</table>
<a href="/Musterı/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musterı/MusterıGetır.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusterıGetır";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
     <div class="form-group">

         @Html.LabelFor(m => m.MUSTERIID)
         @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
         <br />
         @Html.LabelFor(m=>m.MUSTERIAD)
         @Html.TextBoxFor(m=>m.MUSTERIAD,new{ @class="form-control"})
         <br />
         @Html.LabelFor(m=>m.MUSTERISOYAD)
         @Html.TextBoxFor(m=>m.MUSTERISOYAD,new  {@class="form-control"})

     </div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>
    </div>
}

MvcStok/Views/Musterı/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">

    @*<div>
        <label>Müşteri Adı</label>
        <input type="text" class="form-control" name="MUSTERIAD" />
            
    </div>*@
    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m=>m.MUSTERIAD, new {@class="form-control" })
        @Html.ValidationMessageFor(m=>m.MUSTERIAD,"",new {@style ="color:red"})

    </div>
    <div>
        @*<label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />*@
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new {@class="form-control"})
        @Html.ValidationMessageFor(m => m.MUSTERISOYAD, "", new {@style="color:red"})

    </div>
    <div>
        <div style="margin-top:15px"></div>
        <button class="btn btn-info"id="btn1">Müşteri Ekle</button>
        
    </div>
    <script>
        $('#btn1').click(function(){

            alert("Müşteri Ekleme İşlemi Yapıldı...!");
        });
    </script>


</form>